// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vokinneberg/go-url-shortener-ddd/internal/url (interfaces: URLReaderWriter)

// Package url is a generated GoMock package.
package url

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockURLReaderWriter is a mock of URLReaderWriter interface.
type MockURLReaderWriter struct {
	ctrl     *gomock.Controller
	recorder *MockURLReaderWriterMockRecorder
}

// MockURLReaderWriterMockRecorder is the mock recorder for MockURLReaderWriter.
type MockURLReaderWriterMockRecorder struct {
	mock *MockURLReaderWriter
}

// NewMockURLReaderWriter creates a new mock instance.
func NewMockURLReaderWriter(ctrl *gomock.Controller) *MockURLReaderWriter {
	mock := &MockURLReaderWriter{ctrl: ctrl}
	mock.recorder = &MockURLReaderWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLReaderWriter) EXPECT() *MockURLReaderWriterMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockURLReaderWriter) Get(arg0 string) (*URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(*URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockURLReaderWriterMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockURLReaderWriter)(nil).Get), arg0)
}

// Save mocks base method.
func (m *MockURLReaderWriter) Save(arg0 *URL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockURLReaderWriterMockRecorder) Save(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockURLReaderWriter)(nil).Save), arg0)
}
